version: '2'
services:
   bfgminer:
      image: fabriziogaliano/bfgminer:x86

      network_mode: host

      privileged: true

      tty: true

      environment:
         BFG_USER: "fabri555.2"
         BFG_PASSWORD: "2"
         BFG_URL: "stratum+tcp://litecoinpool.org:3333"

      # command: ["/home/bfgminer/bfgminer", "-S", "gridseed:all", "--set-device", "gridseed:clock=800", "--failover-only", "--scrypt", "--userpass", "fabri555.2:2",  "--url", "stratum+tcp://litecoinpool.org:3333"]