version: '2'
services:
   bfgminer:
      image: fabriziogaliano/docker-raspbian-bfgminer:latest

      network_mode: host

      environment:
         BFG_USER: "fabri555.2"
         BFG_PASSWORD: "2"
         BFG_URL: "stratum+tcp://litecoinpool.org:3333"